export const dummydata = {
  "requestId": "3a2da50f-cc47-4654-b815-0dafa5be43e1",
  "result": {
    "iecBillOfEntry": [
      {
        "sourceId_": "549096b9acb2b13c37f6e8176a8f7e7786479d1a",
        "billOfEntryDate": "2023-09-05T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAACG5397FCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 8954873,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7687767",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": null,
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": true,
          "trackingAtIces": null,
          "numberOfQueryRaised": "1",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-09-07T22:40:47.397000+00:00"
      },
      {
        "sourceId_": "ea0e586da748f1668a16f986c7231e37932dad39",
        "billOfEntryDate": "2023-09-04T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAKFS1787LCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "Y",
          "sec48": "N",
          "totalValue": 12830400,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7676090",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": "AAI",
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-09-07T00:11:33.372000+00:00"
      },
      {
        "sourceId_": "38e2e7bd1e7f444014619ec999aae5bc49bdf66c",
        "billOfEntryDate": "2023-09-03T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAACG5397FCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 5275769,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7659778",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": "APR",
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-09-05T19:24:52.272000+00:00"
      },
      {
        "sourceId_": "0173e588f54c1ed5806813789dc7f76625910170",
        "billOfEntryDate": "2023-09-03T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAACG5397FCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 6102811,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7659784",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": "APR",
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-09-05T19:29:35+00:00"
      },
      {
        "sourceId_": "40038d56def2d853c2827d82c2f68373d801fdc8",
        "billOfEntryDate": "2023-08-31T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAKFS1787LCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "N",
          "sec48": "C",
          "totalValue": 3736045.2,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7610302",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": 0,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": {
          "challanNumber": "2045593541",
          "dutyAmount": 0,
          "dutyPaid": null,
          "fineAmount": 50000,
          "interestAmount": 0,
          "modeOfPayment": null,
          "penaltyAmount": 0,
          "totalDuty": 50000,
          "trackingAtIces": null
        },
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-09-03T00:38:28.109000+00:00"
      },
      {
        "sourceId_": "9c14995441daea72e856e99ac6a8040be7230be2",
        "billOfEntryDate": "2023-08-29T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAECE1545KCH003",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "N",
          "sec48": "N",
          "totalValue": 5880600,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7586558",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": 0,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": {
          "challanNumber": "2045573811",
          "dutyAmount": 0,
          "dutyPaid": 10000,
          "fineAmount": 10000,
          "interestAmount": 0,
          "modeOfPayment": "EPAYMENT",
          "penaltyAmount": 0,
          "totalDuty": 10000,
          "trackingAtIces": null
        },
        "port": null,
        "portCode": "MUNDRA SEA (INMUN1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-09-13T23:38:43.789000+00:00"
      },
      {
        "sourceId_": "bbb562cf14893b573c3c4ceeca662486c7aaba68",
        "billOfEntryDate": "2023-08-27T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAACG5397FCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 9524345,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7554434",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": "SUP",
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-30T05:35:42.242000+00:00"
      },
      {
        "sourceId_": "b0ae83a04f4c426396978adaba1b8aa4fde256dc",
        "billOfEntryDate": "2023-08-27T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAACG5397FCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 8751000,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7554509",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": "IMP",
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "1",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-30T06:45:47.466000+00:00"
      },
      {
        "sourceId_": "2b82c4bd22b864ef5d35ca6620030587d6db0563",
        "billOfEntryDate": "2023-08-27T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAACG5397FCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 8751000,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7554461",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": "SUP",
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-30T05:40:34.887000+00:00"
      },
      {
        "sourceId_": "f88b9e8f7ecf206faa23ac522771a2076dfd58ce",
        "billOfEntryDate": "2023-08-25T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAKFS1787LCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "N",
          "sec48": "N",
          "totalValue": 6313442,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7532903",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": 0,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": {
          "challanNumber": "2045520536",
          "dutyAmount": 0,
          "dutyPaid": null,
          "fineAmount": 15000,
          "interestAmount": 0,
          "modeOfPayment": null,
          "penaltyAmount": 0,
          "totalDuty": 15000,
          "trackingAtIces": null
        },
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-28T05:54:46.381000+00:00"
      },
      {
        "sourceId_": "79dad82b6f1081a15f79550672924d5ec6d479db",
        "billOfEntryDate": "2023-08-21T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAKFS1787LCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 13522331,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7445744",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-24T02:26:30.615000+00:00"
      },
      {
        "sourceId_": "ffb9832f503e90f52135b286003ef3d797994ded",
        "billOfEntryDate": "2023-08-05T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AANCA9805HCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 4312440,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7221854",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "MUNDRA SEA (INMUN1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-25T02:43:36.481000+00:00"
      },
      {
        "sourceId_": "00d30291651cebf17d4b987025b118a03852eaf2",
        "billOfEntryDate": "2023-08-05T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AANCA9805HCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 4312440,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7221855",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "MUNDRA SEA (INMUN1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-25T02:44:32.446000+00:00"
      },
      {
        "sourceId_": "23879c192c448968c8883cad5f052f2d61654f6f",
        "billOfEntryDate": "2023-08-05T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAKFS1787LCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 12997398,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7216269",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Under processing",
          "assessmentDate": null,
          "currentQueue": "SUP",
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-08T04:11:20.755000+00:00"
      },
      {
        "sourceId_": "7019e72e831da52321b3d732f83087cd547978c7",
        "billOfEntryDate": "2023-08-05T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AANCA9805HCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 4312440,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7221856",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "MUNDRA SEA (INMUN1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-25T02:44:40.363000+00:00"
      },
      {
        "sourceId_": "87c5cd21820e84e9b7eb0c088294795c5225905f",
        "billOfEntryDate": "2023-08-05T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAKFS1787LCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 7733937,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7218525",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "SAHAR AIR CARGO ACC (INBOM4)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-24T08:09:24.518000+00:00"
      },
      {
        "sourceId_": "2f13ab60b3b79f8051e7204f9e2f5272498d998b",
        "billOfEntryDate": "2023-08-04T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAKFS1787LCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 8246075.5,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7203373",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-07T11:38:40.398000+00:00"
      },
      {
        "sourceId_": "866c8aa46fc1f825034a3a02f2340086a1f8bde6",
        "billOfEntryDate": "2023-07-31T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAKFS1787LCH001",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 12838573,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7132207",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-19T19:23:28.515000+00:00"
      },
      {
        "sourceId_": "116a42298ea398be05b5994a082cc52062f979f3",
        "billOfEntryDate": "2023-07-29T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAECE1545KCH003",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 15387570,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7104577",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "MUNDRA SEA (INMUN1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-18T07:58:49.291000+00:00"
      },
      {
        "sourceId_": "a565a6ebf23e2e3bed5cc5efa52025b0334acd22",
        "billOfEntryDate": "2023-07-29T00:00:00.000000Z",
        "billOfEntryDetails": {
          "chaNumber": "AAECE1545KCH003",
          "appraisingGroup": null,
          "finePenalty": null,
          "firstCheck": "N",
          "grossWeight": null,
          "priorBe": "C",
          "sec48": "N",
          "totalValue": 3969405,
          "totalAssessableValue": null,
          "totalDuty": null,
          "totalPackage": null,
          "trackingAtIces": null,
          "type": "H",
          "wbeNumber": null
        },
        "billOfEntryNumber": "7104974",
        "currentStatus": {
          "appraisalDate": null,
          "appraisement": "Processed",
          "assessmentDate": null,
          "currentQueue": null,
          "examDate": null,
          "oocDate": null,
          "paymentDate": null,
          "queryRaised": null,
          "queryReply": null,
          "replyDate": null,
          "replyStatus": false,
          "trackingAtIces": null,
          "numberOfQueryRaised": "0",
          "numberOfQueryReplied": "0"
        },
        "dutyAmount": null,
        "iec": "0313073295",
        "isFineImposed": null,
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDate": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "MUNDRA SEA (INMUN1)",
        "queue": null,
        "sourceUri": null,
        "timestamp": "2023-08-18T08:44:50.624000+00:00"
      }
    ],
    "iecShippingBill": [
      {
        "sourceId_": "21085f7c4da8a55e432bdae1e79267e20f2b79a2",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-10T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "UASU1071749",
          "egmNumber": "EPTAD-03/52",
          "sealNumber": "SPPL02684162",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278107",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-01-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX082",
            "invoiceDate": "2023-09-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-09T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3170512.8,
          "grossWeight": 20744,
          "jobNumber": "7615234",
          "portOfDischarge": "CAVAN",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 13,
          "jobDate": "2023-08-09T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0810181360600",
          "cinDate": "2023-10-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3090438",
        "sourceUri": null,
        "timestamp": "2023-09-17T17:10:47.766000+00:00"
      },
      {
        "sourceId_": "7151b83845756642db988ebccfc0a1f502a0e8d1",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-10T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "HLBU3338260",
          "egmNumber": "EPTAD-03/52",
          "sealNumber": "SPPL02684156",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278107",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-01-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX076",
            "invoiceDate": "2023-09-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-09T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3170512,
          "grossWeight": 21002,
          "jobNumber": "7615248",
          "portOfDischarge": "CAVAN",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 13,
          "jobDate": "2023-08-09T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0810181327500",
          "cinDate": "2023-10-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3090433",
        "sourceUri": null,
        "timestamp": "2023-09-17T17:15:25.366000+00:00"
      },
      {
        "sourceId_": "e9b81a78d7f4bea27ff9f83548f79a86e44fda08",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-10T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "TCLU6729739",
          "egmNumber": "EPTB2B-12/51",
          "sealNumber": "CUS014393",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX079",
            "invoiceDate": "2023-09-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-09T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 2971987.2,
          "grossWeight": 20585,
          "jobNumber": "7615243",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 36,
          "jobDate": "2023-08-09T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0810181367700",
          "cinDate": "2023-10-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3090436",
        "sourceUri": null,
        "timestamp": "2023-09-17T17:24:15.159000+00:00"
      },
      {
        "sourceId_": "3bd1c26a8915748644e11debde975662c6b40915",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-10T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "KOCU5070291",
          "egmNumber": "EPTAD-02/49",
          "sealNumber": "SPPL02684161",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "277206",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-07-18T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX081",
            "invoiceDate": "2023-09-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-09T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3767400,
          "grossWeight": 15878,
          "jobNumber": "7615244",
          "portOfDischarge": "CAVAN",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-09T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0810181362900",
          "cinDate": "2023-10-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3090440",
        "sourceUri": null,
        "timestamp": "2023-09-17T17:11:03.213000+00:00"
      },
      {
        "sourceId_": "8babf758b63799d6f6126232422b8cf47984ed4e",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-10T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "CMAU7367517",
          "egmNumber": "EPTB2B-10/55",
          "sealNumber": "SPPL02684158",
          "errorMessage": null,
          "egmDate": "2023-08-13T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX078",
            "invoiceDate": "2023-09-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-09T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 4782960,
          "grossWeight": 17201,
          "jobNumber": "7615233",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-09T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0810181317500",
          "cinDate": "2023-10-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3090439",
        "sourceUri": null,
        "timestamp": "2023-09-17T17:10:34.573000+00:00"
      },
      {
        "sourceId_": "6c003d2bafe04c54b268f5fb53c34f7456559638",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-10T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "TGHU9786813",
          "egmNumber": "EPTB2B-10/55",
          "sealNumber": "SPPL02684160",
          "errorMessage": null,
          "egmDate": "2023-08-13T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278160",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX080",
            "invoiceDate": "2023-09-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "2",
            "rewardFlag": "Y",
            "trackingAtIces": null
          },
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-09T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 2812232.2,
          "grossWeight": 18018,
          "jobNumber": "7615249",
          "portOfDischarge": "AEJEA",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-09T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0810181365600",
          "cinDate": "2023-10-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3090434",
        "sourceUri": null,
        "timestamp": "2023-09-17T17:23:37.613000+00:00"
      },
      {
        "sourceId_": "788c61617d0ceb23116de491521473e0a1eb2915",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-09T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "TCKU6260583",
          "egmNumber": "EPTAD-02/49",
          "sealNumber": "SPPL02684153",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX072",
            "invoiceDate": "2023-08-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-09T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3049956,
          "grossWeight": 20708,
          "jobNumber": "7595906",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-09T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0809179532300",
          "cinDate": "2023-09-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3072392",
        "sourceUri": null,
        "timestamp": "2023-09-16T01:03:38.966000+00:00"
      },
      {
        "sourceId_": "609bd8196a561583d1bca3b072de24374a14b97f",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-10T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "SEGU5085864",
          "egmNumber": "EPTB2B-12/51",
          "sealNumber": "SPPL02684157",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX077",
            "invoiceDate": "2023-09-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-09T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 2971987.2,
          "grossWeight": 20603,
          "jobNumber": "7615231",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 36,
          "jobDate": "2023-08-09T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0810181321200",
          "cinDate": "2023-10-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3090431",
        "sourceUri": null,
        "timestamp": "2023-09-17T17:19:07.930000+00:00"
      },
      {
        "sourceId_": "44eab941b8dfd97568f69fe73427a87a9ed0623a",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-09T00:08:00.000000Z",
          "epCopyPrintStatus": "R",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "UACU5645015",
          "egmNumber": "277339",
          "sealNumber": "SPPL02684149",
          "errorMessage": null,
          "egmDate": "2023-08-15T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": null,
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX061",
            "invoiceDate": "2023-07-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3607072.5,
          "grossWeight": 19798,
          "jobNumber": "7565298",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 18,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0809177302900",
          "cinDate": "2023-09-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3044030",
        "sourceUri": null,
        "timestamp": "2023-09-14T12:15:15.480000+00:00"
      },
      {
        "sourceId_": "e8f9e1260f7d4110c442fe6b0345d70253900146",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-09T00:08:00.000000Z",
          "epCopyPrintStatus": "R",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "UACU5598090",
          "egmNumber": "277339",
          "sealNumber": "SPPL02684148",
          "errorMessage": null,
          "egmDate": "2023-08-15T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": null,
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX060",
            "invoiceDate": "2023-07-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3049956,
          "grossWeight": 21256,
          "jobNumber": "7565295",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0809177303700",
          "cinDate": "2023-09-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3044032",
        "sourceUri": null,
        "timestamp": "2023-09-14T12:20:36.563000+00:00"
      },
      {
        "sourceId_": "b06f65e2903f25ea37517148cdff816d15fec08b",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-08T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "TCLU5191973",
          "egmNumber": "EPTB2B-10/55",
          "sealNumber": "SPPL02684146",
          "errorMessage": null,
          "egmDate": "2023-08-13T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX058",
            "invoiceDate": "2023-07-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3049956,
          "grossWeight": 20782,
          "jobNumber": "7568802",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0808176555700",
          "cinDate": "2023-08-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3047249",
        "sourceUri": null,
        "timestamp": "2023-09-14T15:03:02.888000+00:00"
      },
      {
        "sourceId_": "18f252f919bc12063f7af00c949e735a67e48262",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-09T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "BEAU6119340",
          "egmNumber": "EPTB2B-12/51",
          "sealNumber": "SPPL02683534",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX070",
            "invoiceDate": "2023-08-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "2",
            "rewardFlag": "Y",
            "trackingAtIces": null
          },
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 2954952.8,
          "grossWeight": 16936,
          "jobNumber": "7578797",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 32,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0809177939000",
          "cinDate": "2023-09-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3056513",
        "sourceUri": null,
        "timestamp": "2023-09-14T22:59:50.704000+00:00"
      },
      {
        "sourceId_": "db87ce4c496b8df75c382dda1259d2c439a76562",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-09T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "WWWU9713190",
          "egmNumber": "EPTB2B-12/51",
          "sealNumber": "SPPL02683532",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX068",
            "invoiceDate": "2023-08-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "2",
            "rewardFlag": "Y",
            "trackingAtIces": null
          },
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 2954952.8,
          "grossWeight": 17000,
          "jobNumber": "7582344",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 32,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0809177931900",
          "cinDate": "2023-09-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3059829",
        "sourceUri": null,
        "timestamp": "2023-09-15T01:47:40.577000+00:00"
      },
      {
        "sourceId_": "b417e54d8b9423b77facd165a2c55d55a5a276aa",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-09T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "HCIU8022604",
          "egmNumber": "EPTAD-02/49",
          "sealNumber": "SPPL02683531",
          "errorMessage": null,
          "egmDate": "2023-12-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX067",
            "invoiceDate": "2023-08-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "2",
            "rewardFlag": "Y",
            "trackingAtIces": null
          },
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 2954952.8,
          "grossWeight": 16935,
          "jobNumber": "7578796",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 32,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0809177928100",
          "cinDate": "2023-09-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3056515",
        "sourceUri": null,
        "timestamp": "2023-09-14T23:24:03.489000+00:00"
      },
      {
        "sourceId_": "c7079e2672ec4ae20e34a79b81d8d0fa971667cc",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-08T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "HLXU8516021",
          "egmNumber": "EPTB2B-10/55",
          "sealNumber": "SPPL02684151",
          "errorMessage": null,
          "egmDate": "2023-08-13T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX064",
            "invoiceDate": "2023-07-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 1296230.5,
          "grossWeight": 9080,
          "jobNumber": "7568817",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 17,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0808176536100",
          "cinDate": "2023-08-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3047289",
        "sourceUri": null,
        "timestamp": "2023-09-14T14:59:55.372000+00:00"
      },
      {
        "sourceId_": "669baf9a19c33e4c71a19451238c7daa2d25056b",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-08T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "FCIU9156648",
          "egmNumber": "EPTB2B-10/55",
          "sealNumber": "SPPL02684145",
          "errorMessage": null,
          "egmDate": "2023-08-13T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX057",
            "invoiceDate": "2023-07-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3049956,
          "grossWeight": 20897,
          "jobNumber": "7568776",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0808176553000",
          "cinDate": "2023-08-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3047236",
        "sourceUri": null,
        "timestamp": "2023-09-14T15:05:00.311000+00:00"
      },
      {
        "sourceId_": "c38b9125188696d178bf1339797da2afec9a734a",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-08T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "DAYU6108990",
          "egmNumber": "EPTB2B-10/55",
          "sealNumber": "SPPL02684147",
          "errorMessage": null,
          "egmDate": "2023-08-13T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278219",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-02-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX059",
            "invoiceDate": "2023-07-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3049956,
          "grossWeight": 20933,
          "jobNumber": "7568819",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0808176541900",
          "cinDate": "2023-08-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3047279",
        "sourceUri": null,
        "timestamp": "2023-09-14T15:04:22.139000+00:00"
      },
      {
        "sourceId_": "a022023be654a7edca1596d885065988f843719a",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": null,
          "epCopyPrintStatus": null,
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "P",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": null,
        "gatewayEgmStatusEnquiry": null,
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX062",
            "invoiceDate": "2023-07-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3659161,
          "grossWeight": 19915,
          "jobNumber": "7580634",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 26,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": null,
          "cinDate": null
        },
        "shippingBillNumber": "3058194",
        "sourceUri": null,
        "timestamp": "2023-09-15T00:28:48.967000+00:00"
      },
      {
        "sourceId_": "f768ec8c8707d52bb9c9a75e866085a77546bbb5",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": null,
          "epCopyPrintStatus": null,
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "P",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": null,
        "gatewayEgmStatusEnquiry": null,
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX051",
            "invoiceDate": "2023-06-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "NHAVA SHEVA SEA (INNSA1)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 3049956,
          "grossWeight": 20926,
          "jobNumber": "7561988",
          "portOfDischarge": "USCHS",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 40,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": null,
          "cinDate": null
        },
        "shippingBillNumber": "3040974",
        "sourceUri": null,
        "timestamp": "2023-09-14T10:11:28.568000+00:00"
      },
      {
        "sourceId_": "12d53d2e998cf208e127f75b6ebb1fdc17cd0982",
        "currentStatus": null,
        "currentStatusDetails": {
          "warehouseName": null,
          "currentQueue": "HIST",
          "appraisingDate": null,
          "aCAppraisal": null,
          "aCAppraisalDate": null,
          "examMarkId": null,
          "examDate": null,
          "markDate": null,
          "inspEO": null,
          "supdtAOId": null,
          "dbkACId": null,
          "dbkACIdDate": null,
          "dbkSupdtId": null,
          "dbkSupdtDate": null,
          "depbSupdt": null,
          "depbSupdtDate": null,
          "depbLicense": null,
          "depbLicenseDate": null,
          "sampleDrawn": null,
          "testReport": null,
          "leoDate": "2023-08-08T00:08:00.000000Z",
          "epCopyPrintStatus": "Y",
          "printStatus": null,
          "dbkScrollNumber": null,
          "scrollDate": null,
          "egmIntegrationStatus": "Y",
          "trackingAtIces": null
        },
        "drawbackQueryDetails": null,
        "egmStatus": {
          "containerNumber": "INKU6372007",
          "egmNumber": "EPTRK-41/39",
          "sealNumber": "SPPL02684152",
          "errorMessage": null,
          "egmDate": "2023-09-08T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "gatewayEgmStatusEnquiry": {
          "airwayBillNumber": null,
          "comment": null,
          "errorCode": "S",
          "gatewayEgmNumber": "278009",
          "gatewayPortCode": "INNSA1",
          "gatewaySiteId": "INNSA1",
          "gatewayEgmDate": "2023-07-31T00:00:00.000000Z",
          "trackingAtIces": null
        },
        "iec": "0313073295",
        "igstInvoiceDetails": [
          {
            "gstin": "26AXXXXXXXXF1ZQ",
            "igstPaid": null,
            "invoiceNumber": "XXXXXXXXXXX065",
            "invoiceDate": "2023-07-08T00:00:00.000000Z",
            "trackingAtIces": null
          }
        ],
        "itemWiseRewardDetails": [
          {
            "invoiceNumber": "1",
            "itemNumber": "1",
            "rewardFlag": "Y",
            "trackingAtIces": null
          }
        ],
        "kid": null,
        "otherGovtAgencies": null,
        "pan": null,
        "paymentDetails": null,
        "port": null,
        "portCode": "TUMB ICD (INSAJ6)",
        "queryRaised": null,
        "queryReplied": null,
        "roslStatus": null,
        "shippingBillDate": "2023-08-08T00:00:00.000000Z",
        "shippingBillDetails": {
          "chaNumber": "ADQFS4130ECH001",
          "drawback": 0,
          "fobInr": 2733035,
          "grossWeight": 18871,
          "jobNumber": "7568818",
          "portOfDischarge": "USORF",
          "rewardFlag": null,
          "serviceTaxRefund": 0,
          "totalCess": 0,
          "totalDrawbackServiceTaxRefund": 0,
          "totalPackage": 52,
          "jobDate": "2023-08-08T12:08:00.000000Z",
          "trackingAtIces": null,
          "cinNumber": "23PCEG0808176533900",
          "cinDate": "2023-08-08T00:00:00.000000Z"
        },
        "shippingBillNumber": "3047288",
        "sourceUri": null,
        "timestamp": "2023-09-14T14:59:38.273000+00:00"
      }
    ],
    "iecBillOfEntryCount": 912,
    "iecShippingBillCount": 10789
  },
  "statusCode": 101
}
   